variables:
  S3_BUCKET_NAME: "a-ads-blog"

image: node:9-alpine

deploy:
  script:
    - apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ libpng-dev fftw-dev build-base python-dev
    - apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ vips-dev
    - npm install gatsby
    - npm install
    - node_modules/.bin/gatsby build --prefix-paths
    - apk add --no-cache --update python3
    - pip3 install awscli
    - aws s3 cp ./public/ s3://$S3_BUCKET_NAME/blog/ --recursive --acl public-read
    - aws s3 cp --content-type="text/vnd.yaml" --acl public-read --metadata-directive="REPLACE" s3://$S3_BUCKET_NAME/blog/admin/config.yml s3://$S3_BUCKET_NAME/blog/admin/config.yml
  only:
    - master
