image: node:8-alpine

build:
  stage: build
  script:
    - apk add --update --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ --virtual .build-deps libpng-dev vips-dev fftw-dev build-base
    - npm install yarn gatsby
    - node_modules/.bin/yarn install
    - node_modules/.bin/gatsby build

deploy:
  script:
  - apk add --no-cache --update python3
  - pip3 install awscli
#  - aws s3 cp ./ s3://yourbucket/ --recursive --exclude "*" --include "*.html"
