variables:
  PROD_BUCKET: "a-ads-blog"
  STAGE_BUCKET: "a-ads-staging-blog"
  AWS_DEFAULT_REGION: eu-central-1
  REGISTRY_HOST: 461602623056.dkr.ecr.eu-central-1.amazonaws.com
  DOCKER_DRIVER: overlay2
  SSH_PORT: 10115
  TMPDIR: /tmp

image: node:18-alpine


production_deploy:
  when: manual
  retry: 1
  image: $REGISTRY_HOST/aads-ci-blog

  services:
    - $REGISTRY_HOST/aads-ci-blog

  stage: deploy

  before_script:
    - echo 'Starting deploy to production'

  only:
    - master

  script:
    # Update blog
    - cd /data
    - node_modules/.bin/gatsby build --prefix-paths
    - aws s3 cp ./public/ s3://$PROD_BUCKET/blog/ --recursive --acl public-read
    - aws s3 cp --content-type="text/vnd.yaml" --acl public-read --metadata-directive="REPLACE" s3://$PROD_BUCKET/blog/admin/config.yml s3://$PROD_BUCKET/blog/admin/config.yml


staging_deploy:
#  when: manual
  retry: 1
  image: $REGISTRY_HOST/aads-ci-blog

  services:
    - $REGISTRY_HOST/aads-ci-blog

  stage: deploy

  before_script:
    - echo 'Starting deploy to staging'

  only:
    - staging

  script:
    # Update blog
    - cd /data
    - node_modules/.bin/gatsby build --prefix-paths
    - aws s3 cp ./public/ s3://$STAGE_BUCKET/blog/ --recursive --acl public-read
    - aws s3 cp --content-type="text/vnd.yaml" --acl public-read --metadata-directive="REPLACE" s3://$STAGE_BUCKET/blog/admin/config.yml s3://$STAGE_BUCKET/blog/admin/config.yml
