variables:
  S3_PRODUCTION_BUCKET_NAME: "a-ads-blog"
  S3_STAGING_BUCKET_NAME: "a-ads-staging-blog"

image: node:12-alpine

production_deploy:
  before_script:
    - node -v
    - npm install npm@6.14.16 -g
    - npm install

#sed -i -e 's/v3\.11/v3.12/g' /etc/apk/repositories # removed now
  script:
    - set -e -x
    - apk upgrade --available
    - apk add --update --no-cache build-base
    - apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.12/main/ libpng-dev fftw-dev python3-dev libimagequant-dev
    - apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.12/community/ vips-dev
    - node_modules/.bin/gatsby build --prefix-paths
    - apk add --no-cache --update python3 aws-cli
    - aws s3 cp ./public/ s3://$S3_PRODUCTION_BUCKET_NAME/blog/ --recursive --acl public-read
    - aws s3 cp --content-type="text/vnd.yaml" --acl public-read --metadata-directive="REPLACE" s3://$S3_PRODUCTION_BUCKET_NAME/blog/admin/config.yml s3://$S3_PRODUCTION_BUCKET_NAME/blog/admin/config.yml
  only:
    - master  


staging_deploy:
  before_script:
    - node -v
    - npm install npm@6.14.16 -g
    - npm install

#sed -i -e 's/v3\.11/v3.12/g' /etc/apk/repositories # removed now
  script:
    - set -e -x
    - apk upgrade --available
    - apk add --update --no-cache build-base
    - apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.12/main/ libpng-dev fftw-dev python3-dev libimagequant-dev
    - apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.12/community/ vips-dev
    - node_modules/.bin/gatsby build --prefix-paths
    - apk add --no-cache --update python3 aws-cli
    - aws s3 cp ./public/ s3://$S3_STAGING_BUCKET_NAME/blog/ --recursive --acl public-read
    - aws s3 cp --content-type="text/vnd.yaml" --acl public-read --metadata-directive="REPLACE" s3://$S3_STAGING_BUCKET_NAME/blog/admin/config.yml s3://$S3_STAGING_BUCKET_NAME/blog/admin/config.yml
  only:
    - staging
