variables:
  S3_BUCKET_NAME: "a-ads-blog"

image: node:8-alpine

deploy:
  before_script:
    - npm install npm@latest -g
    - npm install

  script:
    - apk add --update --no-cache build-base
    - apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ libpng-dev fftw-dev python-dev libeimagequant
    - apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ vips-dev
    - node_modules/.bin/gatsby build --prefix-paths
    - apk add --no-cache --update python3
    - pip3 install awscli
    - aws s3 cp ./public/ s3://$S3_BUCKET_NAME/blog/ --recursive --acl public-read
    - aws s3 cp --content-type="text/vnd.yaml" --acl public-read --metadata-directive="REPLACE" s3://$S3_BUCKET_NAME/blog/admin/config.yml s3://$S3_BUCKET_NAME/blog/admin/config.yml
  only:
    - master
