[build]
  publish = "public"
  command = "npm run prebuild -- $HEAD && npm i --legacy-peer-deps --force && node_modules/.bin/gatsby clean && node_modules/.bin/gatsby build --prefix-paths && npm run move"
