backend:
  name: gitlab
  repo: Leoplod/aads-blog-gatsby-netlifycms

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: thumbnail, label: Featured Image, widget: image, required: false, default: '' }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: list, default: ["news"] }
      - { name: category, label: Category, widget: relation, collection: blog_categories, valueField: title }
      
  - name: blog_categories
    label: Blog categories
    folder: content/blog_categories
    create: true
    fields: 
      - { name: title, label: Title }
      - { name: order, label: Order, default: 0 }
