backend:
  name: gitlab
  repo: lev/blog
  base_url: https://gitlab0.int.a-ads.com
  api_root: https://gitlab0.int.a-ads.com/api/v4
  auth_endpoint: oauth/authorize
  auth_type: implicit
  app_id: 52373d0f5426390b5ac3bbe0ee0ebe0dba2242f8b03173558db165149c314997

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: blog/assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: slug, label: Slug }
      - { name: tags, label: Tags, widget: list, default: ["news"], required: false }
      - { name: category,
          label: Category,
          widget: relation,
          collection: blog_categories,
          valueField: title,
          searchFields: [title],
          displayFields: [title]
        }
      - { name: thumbnail, label: Featured Image, widget: image, required: false, default: '' }
      - { name: big_picture, label: Square Image, widget: image, required: false, default: '' }
      - { name: body, label: Body, widget: markdown }
      - { name: meta_description, label: Meta Description, required: false, default: '' }
      - { name: meta_keywords, label: Meta Keywords, required: false, default: '' }
      - { name: json_ld, label: Json ld, widget: 'text', required: false, default: '' }

  - name: blog_categories
    label: Blog categories
    folder: content/blog_categories
    create: true
    extension: yml
    fields:
      - { name: title, label: Title }
      - { name: order, label: Order, default: '0' }

  - name: misc
    label: Misc
    files:
      - label: "Main jumbotron"
        name: main_jumbotron
        file: content/misc/main_jumbotron.yml
        create: true
        fields:
          - { label: Path to markdown, name: path, widget: string }
          - { label: Title, name: title, widget: string }
