backend:
  name: gitlab
  repo: Leoplod/aads-blog-gatsby-netlifycms

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: markdown_files/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: thumbnail, label: Featured Image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
